# This is a basic workflow to help you get started with Actions

name: CI-Self Hosted

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ['self-hosted', 'macOS', 'ARM64']
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - name: Set color
        id: color-selector
        run: |
          echo "NAME=HectorJ" >> "$GITHUB_OUTPUT"
          echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
          echo "HOUR=$(date)">> "$GITHUB_OUTPUT"
      #use the output from a command in the previous step.
      
      - name: Get color
        env:
          SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
        run: echo "The selected color is $SELECTED_COLOR"
        
      - name: Get Name
        env:
          NAME: ${{ steps.color-selector.outputs.NAME }}
        run: echo "The name is $NAME"
      # Testing Workflow Commands : 
      
      - name: Test Masking
        run: |
          echo '::add-mask::test'
          echo This is a test

      - name: Create annotation for build error
        run: echo "::error file=app.js,line=1::Missing semicolon"
